stages:
  - build
  - test

variables:
  IMAGE_TAG: $CI_COMMIT_SHA

build-backend:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:v1.9.0-debug
    entrypoint: [""]
  script:
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}/backend"
      --dockerfile "${CI_PROJECT_DIR}/backend/Dockerfile"
      --destination "${CI_REGISTRY_IMAGE}/momo-backend:${IMAGE_TAG}"
      --cache=true
      --cache-ttl=6h

unittest:
  stage: test
  image: golang:alpine
  before_script:
    - apk add build-base
  script:
    - cd backend
    - go test -v ./...

sonarqube-sast:
  stage: test
  image: sonarsource/sonar-scanner-cli:latest
  script:
    - >
      sonar-scanner
      -Dsonar.qualitygate.wait=true
      -Dsonar.projectKey="${SONAR_PROJECT_KEY_BACK}"
      -Dsonar.sources="${CI_PROJECT_DIR}/frontend"
      -Dsonar.host.url="${SONARQUBE_URL}"
      -Dsonar.login="${SONAR_LOGIN_BACKEND}"
